#pragma once

#include "jk_tapdance.h"

#define LGA LGUI_T(KC_A)
#define LAS LALT_T(KC_S)
#define LCD LCTL_T(KC_D)
#define LSF LSFT_T(KC_F)  
#define RGSC RGUI_T(KC_SCLN)
#define RAL RALT_T(KC_L)
#define RCK RCTL_T(KC_K)
#define RSJ RSFT_T(KC_J)
#define CBS LCTL(KC_BSPC)
#define CRA LCTL(KC_RIGHT)
#define CLA LCTL(KC_LEFT)
#define CDEL LCTL(KC_DEL)
#define CHOME LCTL(KC_HOME)
#define CEND LCTL(KC_END)
#define UNDO LCTL(KC_Z)
#define COPY LCTL(KC_C)
#define CUT LCTL(KC_X)
#define PASTE LCTL(KC_V)
#define TDESME TD(TD_ESC_MED)
#define TDSN TD(TD_SPACE_NAV)
#define TDTS TD(TD_TAB_SYM)
#define TDBS TD(TD_BSPC_SYM)
#define TDENMS TD(TD_ENT_MS)
#define TDDM TD(TD_DEL_MED)
